### ISSUE TITLE
My Game Freezes Frequently for a few seconds

### ISSUE THREAD

**Issue by queenellee** [Luna5ama/TrollHack#71] opened 2022-12-21 09:52 UTC
Every minute or so my game will freeze for a few seconds, I am certain that this is because of Trollhack because this only happens when I use Trollhack, this is a major issue and kills me a lot when Crystal Pvping, it happens to lots of other people I know who use it too, please could address this. Thank You

**Comment by Luna5ama** [comment] 2022-12-21 10:05
Duplicate of #65

**Closed by Luna5ama** 2022-12-21 10:05 UTC
Labels: duplicate
